In [5]:
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
# imo
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
vocab_size=len(tokenizer.word_index)+1

In [ ]:
Sequences=tokenizer.texts_to_sequences(docs)
Sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
len(Sequences)

10

In [ ]:
from keras.utils import pad_sequences
sequences=pad_sequences(Sequences,padding='post')
sequences


array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [ ]:
vocab_size = len(tokenizer.word_index) + 1  # Always add +1 for padding and max index

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=2, input_length=5))
model.build(input_shape=(None, None))

model.summary()


d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, None, 2)        │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step
[[[ 0.01169502  0.01521545]
  [ 0.03077419  0.03303428]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702]]

 [[ 0.03077419  0.03303428]
  [ 0.03077419  0.03303428]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702]]

 [[-0.00326518  0.01177356]
  [-0.00326518  0.01177356]
  [-0.01270987 -0.01696593]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702]]

 [[-0.00269152 -0.04305606]
  [-0.00426751 -0.0420038 ]
  [-0.00269152 -0.04305606]
  [ 0.03077419  0.03303428]
  [-0.00269152 -0.04305606]]

 [[ 0.03338305 -0.00423818]
  [-0.01274246  0.00279234]
  [ 0.01828047 -0.04448085]
  [-0.01781106 -0.03960149]
  [ 0.02058519 -0.02861702]]

 [[-0.04535064 -0.04956075]
  [-0.04535064 -0.04956075]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702]]

 [[-0.0037706  -0.03267157]
  [-0.0037706  -0.03267157]
  [ 0.02058519 -0.02861702]
  [ 0.02058519 -0.02861702

In [ ]:
from keras.datasets import imdb
# from keras.preprocessing import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Embedding, Dense, SimpleRNN,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

In [ ]:
X_train=pad_sequences(X_train,padding='post',maxlen=100)
X_test=pad_sequences(X_test,padding='post',maxlen=100)

X_test.shape


(25000, 100)

In [ ]:
X_train.shape

(25000, 100)

In [ ]:
y_test.shape

(25000,)

In [ ]:
vocab_size = 10000  # As per num_words given

In [ ]:
model=Sequential()

model.add(Embedding(vocab_size, 2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.build(input_shape=(None, None))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, None, 2)        │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5


InvalidArgumentError: Graph execution error:

Detected at node sequential_1_1/embedding_1_1/GatherV2 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\tornado\platform\asyncio.py", line 211, in start

  File "C:\Users\sande\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 604, in run_forever

  File "C:\Users\sande\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1909, in _run_once

  File "C:\Users\sande\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\IPython\core\interactiveshell.py", line 3100, in run_cell

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\IPython\core\interactiveshell.py", line 3155, in _run_cell

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\IPython\core\interactiveshell.py", line 3367, in run_cell_async

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\IPython\core\interactiveshell.py", line 3612, in run_ast_nodes

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\IPython\core\interactiveshell.py", line 3672, in run_code

  File "C:\Users\sande\AppData\Local\Temp\ipykernel_18652\374916602.py", line 2, in <module>

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 377, in fit

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 220, in function

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 133, in multi_step_on_iterator

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 114, in one_step_on_data

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 58, in train_step

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\layers\layer.py", line 936, in __call__

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\ops\operation.py", line 58, in __call__

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\models\sequential.py", line 220, in call

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\models\functional.py", line 183, in call

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\ops\function.py", line 177, in _run_through_graph

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\models\functional.py", line 648, in call

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\layers\layer.py", line 936, in __call__

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\ops\operation.py", line 58, in __call__

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\layers\core\embedding.py", line 150, in call

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\ops\numpy.py", line 5581, in take

  File "d:\Project-to-learn\Whatsapp-chat-Analysis-system\.tensorli\Lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 2274, in take

indices[0,18] = 31370 is not in [0, 10000)
	 [[{{node sequential_1_1/embedding_1_1/GatherV2}}]] [Op:__inference_multi_step_on_iterator_2258]