In [1]:
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [2]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [3]:
# imo
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
vocab_size=len(tokenizer.word_index)+1

In [6]:
Sequences=tokenizer.texts_to_sequences(docs)
Sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [7]:
len(Sequences)

10

In [8]:
from keras.utils import pad_sequences
sequences=pad_sequences(Sequences,padding='post')
sequences


array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [9]:
vocab_size = len(tokenizer.word_index) + 1  # Always add +1 for padding and max index

model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=2, input_length=5))
model.build(input_shape=(None, None))

model.summary()


d:\Project-to-learn\.machine\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, None, 2)        │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile('adam','accuracy')

In [11]:
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[[[-0.01569158 -0.00733507]
  [ 0.01886045 -0.0462579 ]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253]]

 [[ 0.01886045 -0.0462579 ]
  [ 0.01886045 -0.0462579 ]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253]]

 [[ 0.00085995  0.04067259]
  [ 0.00085995  0.04067259]
  [-0.04011533  0.02630745]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253]]

 [[ 0.0495054   0.02546361]
  [ 0.04049649 -0.02663437]
  [ 0.0495054   0.02546361]
  [ 0.01886045 -0.0462579 ]
  [ 0.0495054   0.02546361]]

 [[ 0.01402367 -0.03406141]
  [ 0.01855639  0.0262284 ]
  [ 0.00575935 -0.02847596]
  [-0.04047025  0.00342585]
  [ 0.02324403 -0.00640253]]

 [[ 0.0071624   0.04892173]
  [ 0.0071624   0.04892173]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253]]

 [[ 0.00365968  0.02974917]
  [ 0.00365968  0.02974917]
  [ 0.02324403 -0.00640253]
  [ 0.02324403 -0.00640253

In [12]:
from keras.datasets import imdb
# from keras.preprocessing import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Embedding, Dense, SimpleRNN,Flatten

In [13]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

In [14]:
X_train=pad_sequences(X_train,padding='post',maxlen=100)
X_test=pad_sequences(X_test,padding='post',maxlen=100)

X_test.shape


(25000, 100)

In [15]:
X_train.shape

(25000, 100)

In [16]:
y_test.shape

(25000,)

In [17]:
vocab_size = 10000  # As per num_words given

In [18]:
model=Sequential()

model.add(Embedding(vocab_size, 2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.build(input_shape=(None, None))

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, None, 2)        │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5


InvalidArgumentError: Graph execution error:

Detected at node sequential_1_1/embedding_1_1/GatherV2 defined at (most recent call last):
  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main

  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "d:\Project-to-learn\.machine\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\kernelapp.py", line 739, in start

  File "d:\Project-to-learn\.machine\lib\site-packages\tornado\platform\asyncio.py", line 211, in start

  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever

  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once

  File "C:\Users\sande\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute

  File "d:\Project-to-learn\.machine\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell

  File "d:\Project-to-learn\.machine\lib\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell

  File "d:\Project-to-learn\.machine\lib\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell

  File "d:\Project-to-learn\.machine\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner

  File "d:\Project-to-learn\.machine\lib\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async

  File "d:\Project-to-learn\.machine\lib\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes

  File "d:\Project-to-learn\.machine\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code

  File "C:\Users\sande\AppData\Local\Temp\ipykernel_26676\1823951651.py", line 2, in <module>

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 377, in fit

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 220, in function

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 133, in multi_step_on_iterator

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 114, in one_step_on_data

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 58, in train_step

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\layers\layer.py", line 936, in __call__

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\ops\operation.py", line 58, in __call__

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\models\sequential.py", line 220, in call

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\models\functional.py", line 183, in call

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\ops\function.py", line 177, in _run_through_graph

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\models\functional.py", line 648, in call

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\layers\layer.py", line 936, in __call__

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\ops\operation.py", line 58, in __call__

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\layers\core\embedding.py", line 150, in call

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\ops\numpy.py", line 5581, in take

  File "d:\Project-to-learn\.machine\lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 2274, in take

indices[0,6] = 10063 is not in [0, 10000)
	 [[{{node sequential_1_1/embedding_1_1/GatherV2}}]] [Op:__inference_multi_step_on_iterator_2258]