In [51]:
# Dummy input: batch of 4 sequences, length=5, features=3
import numpy as np
seq_len=5
input_size=3
x = np.random.randn(4, seq_len, input_size).astype(np.float32)

In [52]:
x.shape

(4, 5, 3)

In [53]:
x[0]

array([[ 1.3666    ,  0.15871798,  0.47269258],
       [-1.081172  , -0.23460414,  1.9435314 ],
       [ 1.2576255 ,  0.33780402, -1.7377528 ],
       [-1.5820633 ,  1.2235551 , -2.1497047 ],
       [ 1.5408027 , -0.8914579 ,  1.1059728 ]], dtype=float32)

In [54]:
import tensorflow 
from tensorflow import keras
from keras.models import Sequential
from keras.layers import SimpleRNN ,Dense

In [55]:
# Build model
model = Sequential([
    SimpleRNN(4, return_sequences=True, input_shape=(5,3)),  # output full sequence for next RNN
    SimpleRNN(3,return_sequences=True),
    SimpleRNN(2),  # output last timestep only
    Dense(1)       # final output
])
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_47 (SimpleRNN)       │ (None, 5, 4)           │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_48 (SimpleRNN)       │ (None, 5, 3)           │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_49 (SimpleRNN)       │ (None, 2)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71 (284.00 B)

 Trainable params: 71 (284.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print(model.get_weights()[0 ].shape)
model.get_weights()[0]

(3, 4)


array([[ 0.34735978, -0.5231489 , -0.4593589 ,  0.4248166 ],
       [ 0.5834987 ,  0.64241326,  0.75955784,  0.29983974],
       [-0.87552154,  0.8402096 , -0.84316874,  0.48855639]],
      dtype=float32)

In [62]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(4, 4)


array([[ 0.11075258, -0.2655293 ,  0.34553227,  0.89321643],
       [ 0.5000976 ,  0.67923737,  0.5330516 , -0.0662955 ],
       [-0.53498286,  0.6795881 , -0.31549639,  0.39040416],
       [ 0.6718852 ,  0.07931575, -0.70492935,  0.21296465]],
      dtype=float32)