🔹 Task 4: Sequence-to-Sequence — Next Timestep Regression

Goal: Predict the next timestep given a sequence.

Skills: Many-to-many, return_sequences=False for last layer.

In [1]:
import numpy as np 
import tensorflow 
from tensorflow import keras
from keras.layers import SimpleRNN, Dense
from keras.models import Sequential

In [2]:
seq_len=20
feature=5

In [4]:
X=np.random.rand(1000,seq_len,feature).astype(np.float32)

In [6]:
X[1]

array([[0.56397754, 0.72764313, 0.56601083, 0.5603537 , 0.1743707 ],
       [0.5839962 , 0.4638774 , 0.8211844 , 0.26896375, 0.28375918],
       [0.36653516, 0.80273366, 0.3819378 , 0.09617269, 0.4849714 ],
       [0.3965276 , 0.9579973 , 0.13132511, 0.767169  , 0.30778387],
       [0.6545184 , 0.63102454, 0.14770806, 0.5899597 , 0.14013436],
       [0.22077112, 0.1423378 , 0.14746219, 0.34606898, 0.04885016],
       [0.0363934 , 0.2547015 , 0.8327061 , 0.94066507, 0.30540848],
       [0.45522675, 0.60237396, 0.614281  , 0.32376987, 0.47286645],
       [0.02287827, 0.35783115, 0.9666189 , 0.03916213, 0.95061904],
       [0.5641055 , 0.8232632 , 0.6222459 , 0.60472757, 0.25862193],
       [0.9350073 , 0.6251007 , 0.07233644, 0.39104256, 0.9800295 ],
       [0.11819422, 0.47633356, 0.9780757 , 0.0241018 , 0.84313214],
       [0.4150979 , 0.7513124 , 0.29653543, 0.81819874, 0.2246699 ],
       [0.00298654, 0.77537715, 0.5550711 , 0.4327904 , 0.5305917 ],
       [0.7665981 , 0.76674116, 0.

In [13]:
np.sum(X[:,-1,:][1])+0.5

np.float32(3.1770055)

In [7]:
y=np.sum(X[:,-1,:],axis=1,keepdims=True)+0.5

In [14]:
y

array([[3.638797 ],
       [3.1770055],
       [3.1015031],
       [3.0964723],
       [3.755577 ],
       [3.7466483],
       [4.1671677],
       [2.329741 ],
       [3.973033 ],
       [2.1791458],
       [3.343887 ],
       [3.5538273],
       [3.9057608],
       [3.4121928],
       [2.4639475],
       [3.177725 ],
       [3.1973348],
       [4.0752435],
       [3.1587029],
       [3.441545 ],
       [3.3151433],
       [3.398093 ],
       [2.350769 ],
       [4.156359 ],
       [2.6081865],
       [3.415048 ],
       [1.9972403],
       [1.4883024],
       [2.9758518],
       [2.5063722],
       [3.2065196],
       [2.338957 ],
       [2.5696337],
       [3.2794905],
       [1.4062766],
       [3.696713 ],
       [3.5226147],
       [2.950077 ],
       [2.4643025],
       [2.183345 ],
       [3.5417159],
       [3.193045 ],
       [2.7603207],
       [2.2376952],
       [2.177633 ],
       [3.7983308],
       [2.656858 ],
       [3.3353772],
       [3.4593554],
       [3.1554935],


In [20]:
model=Sequential()
model.add(SimpleRNN(20,return_sequences=True,input_shape=(seq_len,feature)))
model.add(SimpleRNN(10,return_sequences=True))
model.add(SimpleRNN(5,return_sequences=True))
model.add(SimpleRNN(2))
model.add(Dense(1))
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_10 (SimpleRNN)       │ (None, 20, 20)         │           520 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_11 (SimpleRNN)       │ (None, 20, 10)         │           310 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_12 (SimpleRNN)       │ (None, 20, 5)          │            80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_13 (SimpleRNN)       │ (None, 2)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 929 (3.63 KB)

 Trainable params: 929 (3.63 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(optimizer='adam',loss='mse')

In [24]:
model.fit(X, y, epochs=100, batch_size=32, verbose=1)

Epoch 1/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0525
Epoch 2/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0492
Epoch 3/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0414
Epoch 4/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0372
Epoch 5/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0345
Epoch 6/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0352
Epoch 7/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0288
Epoch 8/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0317
Epoch 9/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0278
Epoch 10/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0267
Epoch 11/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0243
Epoch 12/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0232
Epoch 13/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0208
Epoch 14/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0202
Epoch 15/100
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0230
Epoc

In [27]:
X[:1][0][0]

array([0.29054332, 0.37592953, 0.37646097, 0.23723486, 0.04247412],
      dtype=float32)

In [28]:
print("Pred:", model.predict(X[:1])[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step
Pred: 3.648017
