#### END TO END MODEL IN REcurrent Neural Network

In [38]:
import numpy as np
import tensorflow 
from tensorflow import keras
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense

In [39]:
num_samples = 500
seq_len = 5
features = 3

In [40]:
X = np.random.rand(num_samples, seq_len, features).astype(np.float32)
y = np.sum(X[:, -1, :], axis=1, keepdims=True)  # sum of last timestep

In [41]:
X

array([[[0.15753032, 0.3697417 , 0.8130707 ],
        [0.54802686, 0.83029246, 0.75995487],
        [0.883893  , 0.44882804, 0.9904922 ],
        [0.28096285, 0.21053918, 0.04107517],
        [0.5404152 , 0.947932  , 0.53006136]],

       [[0.8203996 , 0.05316206, 0.4342099 ],
        [0.07556161, 0.08152882, 0.81841326],
        [0.10636324, 0.6975101 , 0.19896108],
        [0.3435549 , 0.31200925, 0.5457176 ],
        [0.6529352 , 0.8018566 , 0.8822401 ]],

       [[0.73185307, 0.19094275, 0.6459025 ],
        [0.36845222, 0.7764359 , 0.7166563 ],
        [0.0491145 , 0.6045924 , 0.42203218],
        [0.5085361 , 0.63589543, 0.80644935],
        [0.97848195, 0.8789571 , 0.71917695]],

       ...,

       [[0.6090795 , 0.03964379, 0.12201469],
        [0.71883285, 0.76360184, 0.5033216 ],
        [0.4267535 , 0.04885339, 0.7394831 ],
        [0.10054434, 0.19473703, 0.96812624],
        [0.12813102, 0.31894356, 0.9651991 ]],

       [[0.7695309 , 0.40613693, 0.42727324],
        [0.73

In [42]:
y

array([[2.0184088 ],
       [2.3370318 ],
       [2.576616  ],
       [2.180559  ],
       [0.84073114],
       [0.7700052 ],
       [1.0064175 ],
       [1.3728666 ],
       [1.4487188 ],
       [1.5225457 ],
       [1.9301485 ],
       [2.2063463 ],
       [1.0444872 ],
       [0.7503313 ],
       [0.74964136],
       [1.1394012 ],
       [0.3931054 ],
       [1.399829  ],
       [0.99420357],
       [0.6048256 ],
       [0.9024279 ],
       [0.6653157 ],
       [1.6627535 ],
       [1.272233  ],
       [1.3159838 ],
       [0.8569352 ],
       [1.9459517 ],
       [1.8322289 ],
       [2.085608  ],
       [1.2929384 ],
       [2.0213342 ],
       [0.87946355],
       [2.0626755 ],
       [1.1987447 ],
       [2.069511  ],
       [1.3129332 ],
       [2.1022236 ],
       [2.0947647 ],
       [1.3068069 ],
       [1.5402409 ],
       [1.2084062 ],
       [0.98021907],
       [0.94959813],
       [1.5698776 ],
       [1.0726491 ],
       [1.5769107 ],
       [1.4035555 ],
       [1.470

In [43]:
model= Sequential()
model.add(SimpleRNN(5,return_sequences=True,input_shape=(6,3)))
model.add(SimpleRNN(4,return_sequences=True))
model.add(SimpleRNN(2))
model.add(Dense(1))

model.compile(optimizer='adam',loss='mse')

d:\Project-to-learn\.machine\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [44]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_10 (SimpleRNN)       │ (None, 6, 5)           │            45 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_11 (SimpleRNN)       │ (None, 6, 4)           │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_12 (SimpleRNN)       │ (None, 2)              │            14 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 102 (408.00 B)

 Trainable params: 102 (408.00 B)

 Non-trainable params: 0 (0.00 B)

In [45]:
history=model.fit(X,y,epochs=20,batch_size=16,verbose=1)

Epoch 1/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 5.2864
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6519
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9584
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.7290
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.5617
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4660
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3904
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3322
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3095
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2850
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.2606
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2875
Epoch 13/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2608
Epoch 14/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2337
Epoch 15/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2541
Epoch 16/20
32/32 ━

In [46]:
test_sample = np.random.rand(1, seq_len, features).astype(np.float32)
pred = model.predict(test_sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step


In [47]:
print("\nTest sample:\n", test_sample)
print("True sum of last timestep:", np.sum(test_sample[:, -1, :]))
print("Model prediction:", pred[0][0])


Test sample:
 [[[0.66052413 0.9383423  0.37012953]
  [0.7776061  0.70043933 0.94384766]
  [0.6624963  0.9312301  0.8488096 ]
  [0.4084283  0.60884607 0.18619774]
  [0.09143433 0.94507605 0.61422825]]]
True sum of last timestep: 1.6507386
Model prediction: 1.4981974
