That is Transformer Part

Self-Attention

In [1]:
import pandas as pd
import numpy as np 
import os 
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [2]:
# make metrix calculation
# money ,bank ,grows
# That word convert in word embedding

# v1=money
# v2=bank
#v3 =grows
X=np.array([[1, 0, 0],
            [0, 1, 0],
            [0, 0, 1]
])

In [3]:
#initialize random weights
np.random.seed(0)
Wq = np.random.rand(3, 3)
Wk = np.random.rand(3, 3)
Wv = np.random.rand(3, 3)

In [4]:
# Step 3: Create Q, K, V
Q = X @ Wq
K = X @ Wk
V = X @ Wv

In [5]:
Q

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [6]:
K

array([[0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985]])

In [7]:
V

array([[0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329]])

In [8]:
# Step 4: Compute attention scores (dot product)
scores = Q @ K.T

In [9]:
# Step 5: Softmax function
def softmax(x):
    exps = np.exp(x - np.max(x, axis=1, keepdims=True))  # stability
    return exps / np.sum(exps, axis=1, keepdims=True)

In [10]:
softmax_scores = softmax(scores)

In [11]:
# Step 6: Multiply softmax with V
output = softmax_scores @ V

In [12]:
# Final output (like ymoney, ybank, ygrows)
print("Output:\n", output)

Output:
 [[0.63146131 0.66587366 0.71028014]
 [0.5968978  0.66846734 0.67444282]
 [0.62089815 0.67772447 0.70530202]]


#Start with SelfAttention

In [19]:
# "Bank River Man"
Bank = np.array([0.6, 0.4, 0])
River = ([0.6, 0.3, 1])
Man = ([1, 0.3, 0.1])

bank = np.array(Bank).reshape(1, 3)
river = np.array(River).reshape(1, 3)
man = np.array(Man).reshape(1, 3)


X_new= np.array([Bank,River,Man])
X_new



array([[0.6, 0.4, 0. ],
       [0.6, 0.3, 1. ],
       [1. , 0.3, 0.1]])